[mission]
next_page_button_pos = [967, 457] # 锻炉 下一页按钮 位置
refresh_time = 0 #刷新悬赏次数 （眉笔机制）
get_white_mission = false # 是否获取白悬赏 (填否的话，会忽视眉笔机制，至少刷一个能量球悬赏(最多再刷100次))
refresh_pos_x = 165 # 刷新悬赏的横坐标
refresh_pos_y =  [334, 455, 577] # 刷新悬赏的纵坐标
x_range =  [232, 300, 370]  # 可点击悬赏的横坐标
min_radius = 13 # 检查能量球悬赏圆的最小半径
max_radius = 14 # 检查能量球悬赏圆的最大半径
y_diff = 10 # 检查到的 y 的误差范围  刷新悬赏的纵坐标pos - y_diff <= 检查y坐标 <= 刷新悬赏的纵坐标pospos + y_diff
perfect_like = 15 # 1 - 100 越小可以检测到更多的假圆。越大能通过检测的圆就更加接近完美的圆形

[leave_detect]
act_to_leave_page = "定位到有银叶数量界面"
leave_right_down_pos = [728, 598]  # "检测银叶右下角坐标（游戏内的坐标）"
check_box = [40, 22] # "检测银叶的框大小"
back_to_pre_page_act = "回退到检测前界面"
debug = false # 是否显示截图,截图会保存在debug目录

[other]
use_dim = true
rounds = 180 # 每次刷多少场
skill_rounds = 24 # 产球的技能循环次数
start_use_leave = 50 # 开始时,超过这个数量就去遗愿用,小于就去PM刷
leave_leaf = 50 # 刷银叶剩余多少就不刷了

[mode]
current_mod = 1 # 1: 全自动(刷银叶 + 用银叶) 2:kf 练功房用银叶 3：pm刷银叶 4: 测试行为 5：只遗愿刷银叶; 6 测试检测银叶；7 测试获取悬赏
test_act = "" # 在config/act里面 的文件名，不带 .json
task_config = "task_config_1280.json" # 使用的任务配置
is_1280_resolution = true # 决定了用 act 的行为带不带 _1280



[mission_back_1280]
next_page_button_pos = [967, 457] # 锻炉 下一页按钮 位置 1280*720的获取悬赏的配置参考 用的话就把这里的值替换上面的配置
refresh_time = 2 #刷新悬赏次数 （眉笔机制）至少是 1 问就是不想改代码
refresh_pos_x = 165 # 刷新悬赏的横坐标
refresh_pos_y =  [334, 455, 577] # 刷新悬赏的纵坐标
x_range =  [232, 300, 370]  # 可点击悬赏的横坐标
min_radius = 13 # 检查能量球悬赏圆的最小半径
max_radius = 14 # 检查能量球悬赏圆的最大半径
y_diff = 10 # 检查到的 y 的误差范围  刷新悬赏的纵坐标pos - y_diff <= 检查y坐标 <= 刷新悬赏的纵坐标pospos + y_diff
perfect_like = 15 # 1 - 100 越小可以检测到更多的假圆。越大能通过检测的圆就更加接近完美的圆形

[mission_back_1080]
next_page_button_pos = [1451, 663] # 锻炉 下一页按钮 位置  1080p的获取悬赏的配置参考 用的话就把这里的值替换上面的配置
refresh_time = 5 # 刷新悬赏次数 （眉笔机制）
refresh_pos_x = 248 # 刷新悬赏的横坐标
refresh_pos_y =  [480, 663, 846] # 刷新悬赏的纵坐标
x_range =  [248, 602]  # 悬赏的横坐标范围
min_radius = 18 # 检查能量球悬赏圆的最小半径
max_radius = 22 # 检查能量球悬赏圆的最大半径
y_diff = 20 # 检查到的 y 的误差范围  刷新悬赏的纵坐标pos - y_diff <= 检查y坐标 <= 刷新悬赏的纵坐标pospos + y_diff
perfect_like = 20 # 1 - 100 越小可以检测到更多的假圆。越大能通过检测的圆就更加接近完美的圆形
